apiVersion: v1
kind: Service
metadata:
  name: {{ include "lowcoder.fullname" . }}-frontend
  labels:
    {{- include "lowcoder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: lowcoder
      protocol: TCP
      name: lowcoder
    {{- if .Values.frontend.service.nodePort }}
      {{- if or (eq .Values.frontend.service.type "NodePort") (eq .Values.frontend.service.type "LoadBalancer") }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "lowcoder.selectorLabels" (dict "component" "frontend" "Values" .Values "Release" .Release "Chart" .Chart) | nindent 4 }}
