{{- $nameSpace := include "lowcoder.namespace" . -}}
{{- $name := include "lowcoder.fullname" . -}}
{{- $lowcoderDatabase := first .Values.mongodb.auth.databases -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lowcoder.fullname" . }}-node-service
  labels:
    {{- include "lowcoder.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  LOWCODER_PUID: {{ .Values.global.config.userId | default "9001" | quote }}
  LOWCODER_PGID: {{ .Values.global.config.groupId | default "9001" | quote }}
  {{- if .Values.global.config.apiServiceUrl }}
  LOWCODER_API_SERVICE_URL: {{ .Values.global.config.apiServiceUrl | quote }}
  {{- else }}
  LOWCODER_API_SERVICE_URL: "http://{{ $name }}-api-service:{{ .Values.apiService.service.port }}"
  {{- end }}
