name: Node Service
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'server/node-service/**'
      - '.github/workflows/node-service.yml'

permissions:
  contents: read

jobs:
  build-node-service:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'
          cache-dependency-path: 'server/node-service/yarn.lock'
      - name: Install dependencies
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: install
          dir: server/node-service
      - name: Run tests
        uses: borales/actions-yarn@v4.2.0
        with:
          cmd: build
          dir: server/node-service
